#!/usr/bin/env python3

import yaml
from scripts.Driver import Driver
from scripts.Apt import AptDownload

with open('config.yml') as config:
    settings = yaml.load(config, Loader=yaml.FullLoader)

# Download all drivers.
drivers_settings = settings.get('drivers')
for driver in drivers_settings.get('list'):
    Driver(
        url=driver.get('url'),
        filename=driver.get('name'),
        install_commands=driver.get('install_commands'),
        download_dir=drivers_settings.get('download_dir')
    ).download()

# Download all needed deb packages.
deb_settings = settings.get('deb')
AptDownload(
    kernel=deb_settings.get('kernel'),
    packages=deb_settings.get('list'),
    download_dir=deb_settings.get('download_dir')
).download()
